### PR TITLE
NF: Extracted cmake configuration for running some rudimentary smoke tests

### PR DESCRIPTION
**Pull request by yarikoptic**
as I had it in the neurodebian package

This one sits on top of #30 which I had to have locally to make it all build.  So shouldn't be merged as is until decision on #30 is made (thus marked as WiP -- work in progress).  Let's now see if this all would work ;)

### CODE REVIEW

**Comment by yarikoptic** [comment]
woohoo -- works from the first try!
Having this test would assure that SUMA built fine and runs `@DO.examples` successfully

I would be happy to tune it up the way you like it, but it could be a nice start for cmake-ification, although somewhat from the "back" ;)

**Comment by yarikoptic** [comment]
ok -- picked up only testing related patches and placed them on top of current master -- let's see if testing goes smoothly. lXp issue would stay within #30 ;)

**Comment by yarikoptic** [comment]
Yeay!  tests pass! whenever merged, I will adjust #30 to tune only ubuntu  make files and then we could see if it breaks any of our brand new tests somehow ;)

**Comment by afni-rickr** [comment]
Great, thanks!

**Pull request merged**
