### PR TITLE
Make some ci fixes

### PR DESCRIPTION
**Pull request by leej3**
This tries to address the issues in publishing test data with datalad described in https://github.com/afni/afni_ci_test_data/issues/2. 

It also includes a breakage in tests that was fixed in https://github.com/afni/afni/pull/268 but it does not look like that is going to be merged.

A temporary fix for 3dClusterize tests where the output diffing does not occur is added for now to pass the tests until the test data is updated appropriately.

There is still an issue with the compilation of libmri on MacOS described here:
https://github.com/afni/afni/issues/278

Additionally suma is no longer compiling on MacOS... that error looks more extensive.

### CODE REVIEW

**Comment by afni-rickr** [comment]
@leej3, @mrneont That CircleCI change seems good, though let's leave comments about the security issue.  @leej3, we can add those later if you prefer.

**Comment by leej3** [comment]
Aha, thanks for that @afni-rickr.

**Comment by afni-rickr** [comment]
It is nice to see the tests pass again, thanks!

**Comment by mrneont** [comment]
Re: "Additionally suma is no longer compiling on MacOS... that error looks more extensive."  Does this refer to a CircleCi build error for Mac OS?  

If that is the case, I think that is resolved---there was two issues that I could tell, each just involving a tweak of "#include .." statements:  in one case, for SUMA_input.c, an "#include .." pointed to a package that was just on a local machine (but we that dependency wasn't necessary, so could be fixed just by commenting that line); in another case, for 3dNwarpCalc.c, the recent addition of an if-condition required putting two simple "#include .."s in one branch of the condition.  

@leej3 , could you please verify if these have resolved the issue(s) you were referring to?

Thanks.

**Pull request merged**
