### PR TITLE
WIP:Fix suma and add system install management

### PR DESCRIPTION
**Pull request by leej3**
supersedes #127

### CODE REVIEW

**Comment by afni-rickr** [comment]
This provides all 617 executables now.

**Comment by leej3** [comment]
Neat. thanks.

**Comment by leej3** [comment]
I removed the "install" bit of the command so the tests aren't running/they are failing immediately. I'll fix that and then move the f2c changes to another pull request next week.

**Comment by afni-rickr** [comment]
Sounds good, thanks!

**Pull request merged**
