### PR TITLE
gui_fix

### PR DESCRIPTION
**Pull request by leej3**
Segfault when opening AFNI gui. Would be great if @yarikoptic  had a fix...

### CODE REVIEW

**Comment by yarikoptic** [comment]
This PR has no actual test added!

**Comment by leej3** [comment]
correct. now it does!

**Comment by afni-rickr** [comment]
It might make sense to test afni using "afni -no_detach".  Testing while it forks a sub-process might confuse things...

**Comment by yarikoptic** [comment]
> It might make sense to test afni using "afni -no_detach". Testing while it forks a sub-process might confuse things...

sounds good

**Pull request merged**
