### PR TITLE
Packaging additions

### PR DESCRIPTION
**Pull request by TheChymera**
Old work by @leej3 and some additions by me. Work in progress for the time being

### CODE REVIEW

**Comment by afni-rickr** [comment]
I would not go the route of renaming the library, as it really is the same library.  It seems that cmake system has a -DUSE_SYSTEM_F2C=ON flag that you could use if it is already installed.
Turning off whirlgif is really easy (comment it out in src/CMakeLists.txt).  However there is a test to make sure that it is being made, which fails at that point.  It would have to be removed from the test, too.  We can ponder that.

**Comment by TheChymera** [comment]
@afni-rickr this should be ready for review now. The test failure I think is on the test runner side ( `worker 'gw0' crashed while running 'scripts/test_3dTstat.py::test_3dTstat_basic[cvarinv]'` ).

**Comment by TheChymera** [comment]
@afni-rickr would you be interested to merge? this allows me to use CMake for the Gentoo build, and it works.

**Comment by afni-rickr** [comment]
That's great @TheChymera, thanks!

**Pull request merged**
