### PR TITLE
Retrots bids

### PR DESCRIPTION
**Pull request by Shotgunosine**
Just adding a some options to make running RetroTS on BIDS formatted physio files a little bit nicer. Also found a bug where slice_order could not be specified as "custom" as in the documentation, only as "Custom".

### CODE REVIEW

**Comment by leej3** [comment]
Looks like a test data problem. Will sort it out. Cheers

**Comment by leej3** [comment]
@afni-rickr  could you take a look at this please

**Comment by afni-rickr** [comment]
It looks okay (and passes my tests), though is bit arithmetic really desired in the `# Handle file inputs` section?

**Comment by leej3** [comment]
Nice spot, thanks. @Shotgunosine your R is starting to leak through into your daily life.

**Pull request merged**
