### PR TITLE
codespellify the ptaylor dierctory---all gud!

### PR DESCRIPTION
**Pull request by mrneont**

### CODE REVIEW

**Comment by afni-rickr** [comment]
The source of the FileNotFoundError failures is not quite clear.
Looking at the test_cmake_build errors, there are suspicious lines showing:
`[INFO] Remote origin not usable by git-annex; setting annex-ignore` 
before later errors stating:
`'message': 'not available; (Note that these git remotes have annex-ignore ' 'set: origin)'`.

**Comment by yarikoptic** [comment]
> The source of the FileNotFoundError failures is not quite clear. Looking at the test_cmake_build errors, there are suspicious lines showing: `[INFO] Remote origin not usable by git-annex; setting annex-ignore` before later errors stating: `'message': 'not available; (Note that these git remotes have annex-ignore ' 'set: origin)'`.

this is benign: `origin` is github from which you are cloning (as logs show), and thus annex cannot use it (since it cannot host data) and that is what it announces it.  You can see it if you run that command locally:

```shell
❯ datalad clone  https://github.com/afni/afni_ci_test_data.git
[INFO   ] Remote origin not usable by git-annex; setting annex-ignore                                                            
[INFO   ] https://github.com/afni/afni_ci_test_data.git/config download failed: Not Found                                        
[INFO   ] access to 2 dataset siblings afnitestdata, cloud not auto-enabled, enable with:
| 		datalad siblings -d "/tmp/afni_ci_test_data" enable -s SIBLING 
install(ok): /tmp/afni_ci_test_data (dataset)
```

and here (as well as in the log) you can see that it says that 2 remotes (siblings) which can potentially have data are not autoenabled and you need to enable them to make use of them...  but ok -- let's proceed to sample error 

```
[{'action': 'get',
  'annexkey': 'MD5E-s6859--47e2ae1ca5055db65039ad1263ee2970.log',
  'message': 'not available; (Note that these git remotes have annex-ignore '
             'set: origin)',
  'path': '/opt/****/src/tests/****_ci_test_data/sample_test_output/ptaylor/test_3dDTtoNoisyDWI/captured_output/test_3dDTtoNoisyDWI_cmd.log',
  'refds': '/opt/****/src/tests/****_ci_test_data',
  'status': 'error',
  'type': 'file'},
``` 
so where is that file available from?
```
❯ git -C afni_ci_test_data/ annex whereis sample_test_output/ptaylor/test_3dDTtoNoisyDWI/captured_output/test_3dDTtoNoisyDWI_cmd.log
whereis sample_test_output/ptaylor/test_3dDTtoNoisyDWI/captured_output/test_3dDTtoNoisyDWI_cmd.log (1 copy) 
  	69196162-f242-475d-801f-2f3b70fda747 -- afniHQ@safni:~/FOR_TEST_AFNI3/afni/tests/afni_ci_test_data
ok
```

and that is the only place and not enabled... and git-annex knows about following ones (it told us about 2 extra):

```
❯ git -C afni_ci_test_data/ show git-annex:remote.log
9d4e5e64-f657-45dd-8522-57da6a188e86 bucket=afnitestdata-9d4e5e64-f657-45dd-8522-57da6a188e86 chunk=1MiB datacenter=US encryption=none host=s3.amazonaws.com name=afnitestdata port=80 public=yes publicurl=https://afnitestdata-9d4e5e64-f657-45dd-8522-57da6a188e86.s3.amazonaws.com storageclass=STANDARD type=S3 timestamp=1561593429.605446s
9d4e5e64-f657-45dd-8522-57da6a188e86 bucket=afnitestdata-9d4e5e64-f657-45dd-8522-57da6a188e86 chunk=1MiB datacenter=US encryption=none host=s3.amazonaws.com name=afnitestdata port=80 public=yes publicurl=https://afnitestdata-9d4e5e64-f657-45dd-8522-57da6a188e86.s3.amazonaws.com storageclass=STANDARD type=S3 timestamp=1587577658.551724s
c1ce38d5-c2ef-48c6-a1f2-e207215d0717 autoenable=true location=https://afni.nimh.nih.gov/pub/dist/data/afni_ci_test_data/.git name=afni_ci_test_data type=git timestamp=1559491237.492276s
d59196e6-1a91-4da3-9c40-b961adf87c58 bucket=cloud-d59196e6-1a91-4da3-9c40-b961adf87c58 chunk=1MiB datacenter=US encryption=none host=s3.amazonaws.com name=cloud port=80 storageclass=STANDARD type=S3 timestamp=1561589473.327923s
```
so `69196162-f242-475d-801f-2f3b70fda747` is not one of those, and I think you should strive to copy your data to one of those "public" ones as you did for other files:

```
❯ git -C afni_ci_test_data/ annex whereis sample_test_output/ptaylor/
...
whereis sample_test_output/ptaylor/test_3dTrackID_PROB/o.3dTrackID_PROB_002.niml.dset (1 copy) 
  	69196162-f242-475d-801f-2f3b70fda747 -- afniHQ@safni:~/FOR_TEST_AFNI3/afni/tests/afni_ci_test_data
ok
whereis sample_test_output/ptaylor/test_3dTrackID_PROB/o.3dTrackID_PROB_003.grid (7 copies) 
  	2f076131-14dd-486b-9b73-b02432719bb9 -- afni_user@bb1574279611:/opt/afni/src/tests/afni_ci_test_data
   	426b512c-f060-43d6-834d-b018a038b296 -- afni_user@bcf8dab82991:/opt/afni/src/tests/afni_ci_test_data
   	493d8f17-eac9-439c-ba89-d10535fdc6bb -- rodgersleejg@MH02131978MACLT:/saved/afni/tests/afni_ci_test_data
   	69196162-f242-475d-801f-2f3b70fda747 -- afniHQ@safni:~/FOR_TEST_AFNI3/afni/tests/afni_ci_test_data
   	77c2f7ba-55ce-483d-9856-bbb1ad2de248 -- rodgersleejg@MH02131978MACLT:/saved/afni/tests/afni_ci_test_data
   	a927c1fa-b536-45c2-ab21-205f6227f03d -- rodgersleejg@promethium.nimh.nih.gov:/store/data/rodgersleejg/afni/tests/afni_ci_test_data
   	c1ce38d5-c2ef-48c6-a1f2-e207215d0717 -- AFNI server for storing data for cheap. Not always available and requires ssh key to upload though. [afni_ci_test_data]
ok
whereis sample_test_output/ptaylor/test_3dTrackID_PROB/o.3dTrackID_PROB_003.niml.dset (1 copy) 
  	69196162-f242-475d-801f-2f3b70fda747 -- afniHQ@safni:~/FOR_TEST_AFNI3/afni/tests/afni_ci_test_data
ok
whereis sample_test_output/ptaylor/test_3dVecRGB_to_HSL/captured_output/test_3dVecRGB_to_HSL_cmd.log (1 copy) 
  	69196162-f242-475d-801f-2f3b70fda747 -- afniHQ@safni:~/FOR_TEST_AFNI3/afni/tests/afni_ci_test_data
...
```
so I see that some files were copied e.g. to c1ce38d5-c2ef-48c6-a1f2-e207215d0717 which was actually autoenabled and thus listed as `[afni_ci_test_data]` and listed among remotes of that clone
```
❯ git -C afni_ci_test_data/ remote
afni_ci_test_data
origin
```

ok, I remember there were some instructions @leej3 left ... yeap -- in https://github.com/afni/afni_ci_test_data/#updating-sample-test-data step 5:

```
datalad publish --transfer-data=all --to=origin
datalad publish --transfer-data=all --to=afni_ci_test_data
```

besides I think it better be in the opposite order since otherwise you would not share new updated git-annex branch with updated information that you did push data to afni_ci_test_data . Or even better update a litte:

-  configure remote origin to also depend on pushing data to afni_ci_test_data:
```
 datalad siblings configure -s origin --publish-depends afni_ci_test_data
```
to be done as step 0 ie once after initial `datalad install`
- use `push` not `publish`:

```
datalad push --to=origin
```

which should first push all new data to `afni_ci_test_data` and then push updated state to `origin` (github)

**Comment by mrneont** [comment]
Hi, @yarikoptic -

Thanks for digging into this in depth.  I should have mentioned the updated schema of what was done, because we did update some of the commands from what John had listed, based on our last conversation with you a couple years ago.

```
# get AFNI binaries
git clone https://github.com/afni/afni.git

# make a new branch
cd afni
git checkout -b update_test_ci

# activate env (which has The Datalad) from necessary location
cd tests
conda activate afni_dev

# get repo --- can install this way, rather than with full link
datalad install afni_ci_test_data

# in some cases, we might only run a subset of tests that have changed, but here
# we ran *all* ptaylor tests, with --create-sample-output to denote these are to be The New Answers
./run_afni_tests.py                            \
    --abin=~/tmp_afni/build_src/linux_ubuntu_16_64  \
    --file scripts/test_ptaylor.py \
    -e='--runveryslow --create-sample-output'  \
    -u                                         \
    -v verbose                                 \
    local

# if happy, sync over last run_afni_tests.py results;
# NB: the timestamp is part of the output from the previous command
rsync -aP                                                    \
    sample_output_of_tests/sample_output_<TIMESTAMP>/  \
    afni_ci_test_data/sample_test_output/

# go into datalad repo and make a commit message
cd afni_ci_test_data
datalad save -m 'update tests_ptaylor'

# publish to both origin and afni_ci_test_data 
datalad push
```

**Comment by mrneont** [comment]
... but should I have also done Step 8 from John's instructions:
```
cd ~/afni # or the path to your afni source code
git add tests/afni_ci_tests_data
git commit -m 'update data for tests'
```
Is that the problem?

**Comment by yarikoptic** [comment]
> ... but should I have also done Step 8 from John's instructions:
> 
> ```
> cd ~/afni # or the path to your afni source code
> git add tests/afni_ci_tests_data
> git commit -m 'update data for tests'
> ```
> 
> Is that the problem?

I don't think so. On the script above I don't know what your are pushing and where, likely only to GitHub, you never push data.  Do that siblings command I listed

**Comment by mrneont** [comment]
So, just to check, the recommendation is that I run the following, where the triple-hashed parts are new or tweaks to what was there before:

```
# get AFNI binaries
git clone https://github.com/afni/afni.git

# make a new branch
cd afni
git checkout -b update_test_ci

# activate env (which has The Datalad) from necessary location
cd tests
conda activate afni_dev

# get repo --- can install this way, rather than with full link
datalad install afni_ci_test_data

### configure remote origin to also depend on pushing data to afni_ci_test_data
datalad siblings configure -s origin --publish-depends afni_ci_test_data

# in some cases, we might only run a subset of tests that have changed, but here
# we ran *all* ptaylor tests, with --create-sample-output to denote these are to be The New Answers
./run_afni_tests.py                            \
    --abin=~/tmp_afni/build_src/linux_ubuntu_16_64  \
    --file scripts/test_ptaylor.py \
    -e='--runveryslow --create-sample-output'  \
    -u                                         \
    -v verbose                                 \
    local

# if happy, sync over last run_afni_tests.py results;
# NB: the timestamp is part of the output from the previous command
rsync -aP                                                    \
    sample_output_of_tests/sample_output_<TIMESTAMP>/  \
    afni_ci_test_data/sample_test_output/

# go into datalad repo and make a commit message
cd afni_ci_test_data
datalad save -m 'update tests_ptaylor'

### publish to both origin and afni_ci_test_data 
datalad push --to=origin
```

Is that looking correct to you?

**Comment by yarikoptic** [comment]
No

**Comment by mrneont** [comment]
Okeydoke.  Um, is there something particular you would suggest that I fix/adjust?

**Comment by yarikoptic** [comment]
now that I am at a keyboard -- you need to run `datalad siblings configure -s origin --publish-depends afni_ci_test_data` inside the `afni_ci_test_data`, so do

```
datalad -C afni_ci_test_data siblings configure -s origin --publish-depends afni_ci_test_data
```

**Comment by mrneont** [comment]
Hi, Yarik-

Thanks for the further suggestions and updates.

After merging in this PR (https://github.com/afni/afni_ci_test_data/pull/7) to the master branch, we tried the following on our main machine for running the tests:
```
# make a new dir
cd
mkdir FOR_TEST_AFNI5

# get AFNI binaries
cd FOR_TEST_AFNI5

# get AFNI binaries
git clone https://github.com/afni/afni.git

# make a new branch (branch name doesn't/shouldn't matter)
cd afni
git checkout -b update_test_ci

# activate env (which has The Datalad) from necessary location
cd tests
conda activate afni_dev

# get repo --- can install this way, rather than with full link
datalad install afni_ci_test_data

##### note about datalad ver on safni:
#####    $ datalad --version
#####    datalad 0.13.6

### configure remote origin to also depend on pushing 
### data to afni_ci_test_data
datalad -C afni_ci_test_data                    \
    siblings configure -s origin                \
    --publish-depends afni_ci_test_data

##### UNANNEXING, onetime step (?)
cd afni_ci_test_data/
git annex unannex * ; datalad save -m 'unannex and annex add all files'
cd ..

# in some cases, we might only run a subset of tests that have
# changed, but here we ran *all* ptaylor tests, with
# --create-sample-output to denote these are to be The New Answers
./run_afni_tests.py                            \
    --abin=~/tmp_afni/build_src/linux_ubuntu_16_64  \
    --file scripts/test_ptaylor.py \
    -e='--runveryslow --create-sample-output'  \
    -u                                         \
    -v verbose                                 \
    local

# if happy, sync over last run_afni_tests.py results;
# NB: the timestamp is part of the output from the previous command
rsync -aP                                                    \
    sample_output_of_tests/sample_output_<TIMESTAMP>/ptaylor/  \
    afni_ci_test_data/sample_test_output/ptaylor/

# go into datalad repo and make a commit message
cd afni_ci_test_data
datalad save -m 'update tests_ptaylor, Mar 20, 2023, after annex step'

### publish to both origin and afni_ci_test_data 
datalad push --to=origin
```

... but this led to this error:
```
datalad push --to=origin
Push to 'origin':  25%|███████████████▊                                               | 1.00/4.00 [00:00<00:00, 6.73k Steps/s]Username for 'https://github.com': afniHQ
Password for 'https://afniHQ@github.com': 
                                                                                                                             CommandError: 'git annex copy --batch -z --to afni_ci_test_data --json --json-error-messages --json-progress --auto --fast' failed with exitcode 1 under /home/afniHQ/FOR_TEST_AFNI5/afni/tests/afni_ci_test_data                                            
git-annex: copy: 115 failed
```

At this point, I think it might be best to Zoom about this.  Would that be possible?  We will email you.

**Comment by yarikoptic** [comment]
instead of 

```
# go into datalad repo and make a commit message
cd afni_ci_test_data
datalad save -m 'update tests_ptaylor, Mar 20, 2023, after annex step'

### publish to both origin and afni_ci_test_data 
datalad push --to=origin
```

which created a new commit withi nafni_ci_test_data and pushed it to the remote, but left that state UNKNOWN to your `afni` repository outside I would have

```shell
# save changed state of the subdataset with new results (-d .. because we are under tests/)
datalad save -d .. -m 'update tests_ptaylor, Mar 20, 2023, after annex step' -r afni_ci_test_data

### publish to both origin and afni_ci_test_data 
datalad push --to=origin -r
```

**Pull request merged**
